### ISSUE TITLE
Description not properly implemented

### ISSUE THREAD

**Issue by dasistwas** [atlet/moodle-mod_booking#16]
The description of a booking option is not properly implemented: There is now the old "Description" setting. Additional description settings for "Booking option text" before/after/completed. The problem: The regular description text will always be displayed and "Show description" link shows potential duplicate text.
Also be sure to have the link "Show description" in `<div>` container, otherwise it is not really rendered nicely.

So instead of adding a before text, let the standard description be the before and the default description. The rest is optional. The other possibility is to delete the default description, but then you must do a proper upgrade and move default description to the before/default description.

**Comment by atlet** [comment]
This is not meant as description, but as additional instructions for each option. Description remains as is, this 3 additional fields (before/after/completed) are meant for special case as one of user expressed interest in it.

For div it's a valid point and I'll fix this. If additional fields are bothering you, I can add a global settings to hide this fields.

**Comment by dasistwas** [comment]
If so, then the wording is misleading and should be adjusted. other things are OK. I will do the wording, that's not a big deal
