### ISSUE TITLE
Drop down menu for booking options on Essential Theme doesn't work

### ISSUE THREAD

**Issue by demontech** [atlet/moodle-mod_booking#18]
Hi Andraz,

Installed the latest version on M3.3 and the drop down menu for the settings of the booking option doesn't work on the Essential theme. It works on boost and clean. 

![image](https://user-images.githubusercontent.com/8148238/31636479-6e31429e-b27f-11e7-8472-73cd3a9e0835.png)

Before having this dropdown, it was easier to get to edit the booking option or to delete it, the icons where right there so you have to click on them only once, now there's an extra step to get to them.

My recommendation and to fix this issue is to bring back the icons the way they were before. Easy access, that's what teachers want instead of the "extra click".

Nice job on this plugin!

**Comment by jharej** [comment]
I vote against this recommendation. Moodle moved to new UI principles and last used approach follows this new guidelines.

**Comment by atlet** [comment]
I found problem with Essential theme. It does not support drop down menu, so that's the reason, why is not working.
