### ISSUE TITLE
Booking Index

### ISSUE THREAD

**Issue by demontech** [atlet/moodle-mod_booking#28]
Hi Andraz,

I remembered that you fixed this issue before. The list of booking is not displaying their names when a student is booked. Going to course menu (http://moodleurl/mod/booking/index.php?id="course_id") and listing all the bookings was really handy for the student to see what bookings they have enrolled, but not now it shows either 0 or 1 = amount of bookings instead of the name of the booking option.

![image](https://user-images.githubusercontent.com/8148238/35140019-7d47fa6e-fcaa-11e7-9100-ffd551740cfb.png)

Thank you in advance for taking a look at this issue!

**Comment by dasistwas** [comment]
That is more kind of nice to have or has to be contracted to be solved.

**Comment by atlet** [comment]
Fixed.
