### ISSUE TITLE
Error when deleting a booking option

### ISSUE THREAD

**Issue by demontech** [atlet/moodle-mod_booking#5]
Hi Andraz,

I'm getting this error when I tried to delete a booking option in M3.0 and your latest develop version:

![image](https://cloud.githubusercontent.com/assets/8148238/19504120/c5c57cd6-956c-11e6-8293-7c9bde0e78f1.png)

Thanks!

**Comment by atlet** [comment]
Is thi still an issue?

**Comment by demontech** [comment]
It was happening for some booking not for all of them. I ended up deleted them from the database.

very strange
