### ISSUE TITLE
Activity Completion report doesn't show 1 for completed or 0 for no completed

### ISSUE THREAD

**Issue by demontech** [atlet/moodle-mod_booking#6]
Hi Andraz,

I'm using your latest version, and when I download the activity completion report (.csv) instead of showing 1s or 0s, it shows & #x2713;  instead of 1 and blank instead of 0. It shows the check mark on the html report for completers.

![image](https://cloud.githubusercontent.com/assets/8148238/21790626/7cf26fca-d692-11e6-9ef3-bc182a027b9d.png)

![image](https://cloud.githubusercontent.com/assets/8148238/21790590/418e2a78-d692-11e6-962a-dc672ab1f3b4.png)

Thanks!

**Comment by atlet** [comment]
I see where is the problem. I'll fix this.

**Comment by atlet** [comment]
Fixed in develop branch.
